from itertools import combinations

n=1
for i in range(1, 6):
    for j in combinations(['favourite','learning','mastered','tag','date','last'], i):
        print(j)
        
        
('favourite',)
('learning',)
('mastered',)
('tag',)
('date',)
('last',)
('favourite', 'learning')
('favourite', 'mastered')
('favourite', 'tag')
('favourite', 'date')
('favourite', 'last')
('learning', 'tag')
('learning', 'date')
('learning', 'last')
('mastered', 'tag')
('mastered', 'date')
('mastered', 'last')
('tag', 'date')
('tag', 'last')
('date', 'last')
('favourite', 'learning', 'tag')     
('favourite', 'learning', 'date')
('favourite', 'learning', 'last')
('favourite', 'mastered', 'tag')
('favourite', 'mastered', 'date')
('favourite', 'mastered', 'last')
('favourite', 'tag', 'date')
('favourite', 'tag', 'last')
('favourite', 'date', 'last')
('learning', 'tag', 'date')
('learning', 'tag', 'last')
('learning', 'date', 'last')
('mastered', 'tag', 'date')
('mastered', 'tag', 'last')
('mastered', 'date', 'last')
('tag', 'date', 'last')
('favourite', 'learning', 'tag', 'date')
('favourite', 'learning', 'tag', 'last')
('favourite', 'learning', 'date', 'last')
('favourite', 'mastered', 'tag', 'date')
('favourite', 'mastered', 'tag', 'last')
('favourite', 'mastered', 'date', 'last')
('favourite', 'tag', 'date', 'last')
('learning', 'tag', 'date', 'last')
('mastered', 'tag', 'date', 'last')
('favourite', 'learning', 'tag', 'date', 'last')
('favourite', 'mastered', 'tag', 'date', 'last')

